In [1]:
import os
os.chdir('../')

In [2]:
from app.data_core.trade_history import load_historical_db, load_daily_trades, filter_scrips, merge_company_details_and_filter, final_data_cleanup
from app.core.config import settings

In [3]:
settings.daily_trades_csv_path

'/Users/robinakan/projects/nepse-analytics-backend/dependency/daily_trades_repo/data'

In [4]:
trade_db = load_historical_db(settings.daily_trades_csv_path)

/Users/robinakan/projects/nepse-analytics-backend/app/data_core/trade_history.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  latest["diff"] = None

Median Trading Days in past 30 days : 1.0
Filtered out Following Stocks :  ['ADBLD83', 'ALICLP', 'BOKD86', 'CCBD88', 'CIZBD86', 'CIZBD90', 'EBLD85', 'EBLD86', 'FMDBLP', 'GBILD86/87', 'GBIMEP', 'GWFD83', 'HBLD83', 'HBLD86', 'HBLPO', 'ICFCD83', 'ILBSP', 'JBBD87', 'JBBLPO', 'KBLD86', 'KBLD89', 'KBLPO', 'KSBBLD87', 'KSY', 'LBLD86', 'LBLD88', 'MBLD2085', 'MBLD87', 'MBLPO', 'MFLD85', 'MLBLD89', 'MND84/85', 'NABILD87', 'NBBD2085', 'NBLD82', 'NBLD85', 'NCCD86', 'NIBD2082', 'NIBD84', 'NICAD 85/86', 'NICAD8182', 'NICAD85/86', 'NICD83/84', 'NICD88', 'NIFRAUR85/86', 'NMBD2085', 'NMBD87/88', 'NMBPO', 'NMLBBL', 'NRICP', 'PBD85', 'PBLD84', 'PBLD86', 'PBLD87', 'PCBLP', 'PMLIP', 'PRVUPO', 'RBBD83', 'SADBLP', 'SBD87', 'SBIBD86', 'SBID83', 'SBLD2082', 'SBLD83', 'SBLD84', 'SBLD89', 'SCBD', 'SDBD87', 'SIFCPO', 'SJLICP', 'SLBSL', 'SPILPO', 'SRBLD83', 'SRD80', 'UNL', 'VLBSPO']
ERROR << 'HIDCLP' >>  : HIDCLP
ERROR << 'NIMBPO' >>  : NIMBPO
ERROR << 'RBCLPO' >>  : RBCLPO
ERROR << 'HEIP' >>  : HEIP
ERROR Expecting value: line 1 column 1 (char 0) :: while loading :  ./app/data_core/constants/company_details/ALICL.json
These stocks have listed shares < 100. Can you believe it ?  []
 Consumed Memory of all_dfs in MB :  138.07349109649658

,Symbol,Conf.,Open,High,Low,Close,VWAP,Vol,Prev. Close,Turnover,...,day_of_week,sector,company_name,symbol,instrument,stockListedShares,publicShares,publicPercentage,promoterShares,promoterPercentage
0,ACLBSL,34.35,577.0,577.0,570.0,577.0,572.65,0.511,578.00,"292,623.30",...,Thursday,Microfinance,Aarambha Chautari Laghubitta Bittya Sanstha Li...,ACLBSL,Equity,3671435.0,1334566.0,36.3500,2336869.0,63.6500
1,ADBL,30.73,254.0,257.0,252.0,254.0,254.26,17.649,256.50,"4,487,409.40",...,Thursday,Commercial Banks,Agricultural Development Bank Limited,ADBL,Equity,134516742.0,65913203.0,49.0000,68603539.0,51.0000
2,AHL,0.0,298.8,328.6,298.8,328.6,327.80,3.220,298.90,"1,055,530.80",...,Thursday,Hydro Power,Asian Hydropower Limited,AHL,Equity,3400000.0,1180000.0,34.7100,2220000.0,65.2900
3,AHPC,36.04,306.0,306.0,294.5,297.0,296.48,50.494,300.00,"14,970,508.70",...,Thursday,Hydro Power,Arun Valley Hydropower Development Co. Ltd.,AHPC,Equity,37359252.0,11207776.0,30.0000,26151476.0,70.0000
4,AKJCL,43.01,226.0,229.8,224.0,224.8,225.68,24.209,228.00,"5,463,461.50",...,Thursday,Hydro Power,Ankhu Khola Jalvidhyut Company Limited,AKJCL,Equity,8000000.0,1999998.0,25.0000,6000002.0,75.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145362,USHL,-,520.0,560.8,520.0,552.9,552.55,88.451,509.90,"48,873,282.20",...,Monday,Hydro Power,Upper Syange Hydropower Limited,USHL,Equity,2200000.0,870000.0,39.5455,1330000.0,60.4545
145363,USLB,-,963.0,979.0,950.0,954.0,957.56,2.182,964.50,"2,089,404.40",...,Monday,Microfinance,Unnati Sahakarya Laghubitta Bittiya Sanstha Li...,USLB,Equity,2468660.0,687062.0,30.0000,1781598.0,70.0000
145364,VLBS,-,655.0,655.0,628.0,639.0,634.94,0.681,648.00,"432,396.50",...,Monday,Microfinance,Vijaya laghubitta Bittiya Sanstha Ltd.,VLBS,Equity,7450404.0,1908349.0,30.0000,5542055.0,70.0000
145365,VLUCL,-,515.0,537.0,515.0,530.2,530.20,30.539,525.00,"16,191,686.00",...,Monday,Hydro Power,Vision Lumbini Urja Company Limited,VLUCL,Equity,19125000.0,3825000.0,20.0000,15300000.0,80.0000
145366,WNLB,-,874.0,888.0,858.0,875.0,863.11,0.614,874.00,"529,946.50",...,Monday,Microfinance,Wean Nepal Laghubitta Bittiya Sanstha Limited,WNLB,Equity,792113.0,237633.0,30.0000,554480.0,70.0000

In [10]:
trade_db.sector.unique()

array(['Microfinance', 'Commercial Banks', 'Hydro Power', 'Tradings',
       'Finance', 'Manufacturing And Processing', 'Hotels And Tourism',
       'Investment', 'Development Banks', 'Non Life Insurance',
       'Life Insurance', 'Others'], dtype=object)

In [20]:
trade_db.groupby('sector').apply(lambda x : x)

/var/folders/5q/d5sngbr11bj5s27jzhrdww2r0000gn/T/ipykernel_38277/3961039351.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  trade_db.groupby('sector').apply(lambda x : x.stockListedShares.median())

sector
Commercial Banks                146940230.0
Development Banks                32811648.0
Finance                           9461152.0
Hotels And Tourism               15340910.0
Hydro Power                      11000000.0
Investment                       25740000.0
Life Insurance                   45455721.0
Manufacturing And Processing     26725233.0
Microfinance                      4155278.0
Non Life Insurance               20123607.0
Others                          128135438.0
Tradings                          3207171.0
dtype: float64

In [13]:
MAX_LISTED_SHARE = 1000000000 ## 1 Billion.
from app.data_core.constants import SECTORS

from dataclasses import dataclass
@dataclass
class FilterParam:
    min_val : int
    max_val: int
    sort: str = ""


from typing import Union
def get_data_by_params(
        df,
        sectors=[    "Microfinance",
    "Commercial Banks",
    "Hydro Power"], 
        start_date:str="2023-01-01",
        end_date: str="2024-01-01",
        top_n:int=3,
        sort_by: Union[str | list]=[],
        listed_share: [0, MAX_LISTED_SHARE, false]
        max_listed_share=MAX_LISTED_SHARE,
        min_listed_share=1000,
        company_names=["NABIL", "API"], 
        ):
    
    """
    `top_n` : Choose only first 3 stocks from each sector
    `sort_by` : How to sort the top_n from each sector.
        Options are -> ['']
    """
    if top_n and top_n > 0:
        assert sort_by is not None, "Provide params to sort at sector level"
    df = df[ (df['sector'].isin(sectors)) & (df.date_scraped >= start_date) 
            & (df.date_scraped <= end_date) & (df.stockListedShares >= min_listed_share)
            & (df.stockListedShares <= max_listed_share)]
    

    


    return

0         63.65
1         51.00
2         65.29
3         70.00
4         75.00
          ...
145934    51.00
145935     0.00
145936    70.00
145937    70.00
145938    70.00
Name: promoterPercentage, Length: 125366, dtype: float64

In [14]:
trade_db.publicPercentage

0          36.35
1          49.00
2          34.71
3          30.00
4          25.00
           ...
145934     49.00
145935    100.00
145936     30.00
145937     30.00
145938     30.00
Name: publicPercentage, Length: 125366, dtype: float64